// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"module4/internal/biz"
	"module4/internal/conf"
	"module4/internal/data"
	"module4/internal/server"
	"module4/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	monitorRepo := data.NewMonitorRepo(dataData, logger)
	monitorUsecase := biz.NewMonitorUsecase(monitorRepo, logger)
	monitorService := service.NewMonitorService(monitorUsecase)
	httpServer := server.NewHTTPServer(confServer, monitorService, logger)
	grpcServer := server.NewGRPCServer(confServer, monitorService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
