// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.3.1

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type MonitorHTTPServer interface {
	CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthReply, error)
}

func RegisterMonitorHTTPServer(s *http.Server, srv MonitorHTTPServer) {
	r := s.Route("/")
	r.GET("/checkhealth", _Monitor_CheckHealth0_HTTP_Handler(srv))
}

func _Monitor_CheckHealth0_HTTP_Handler(srv MonitorHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckHealthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.healthz.v1.Monitor/CheckHealth")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckHealth(ctx, req.(*CheckHealthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckHealthReply)
		return ctx.Result(200, reply)
	}
}

type MonitorHTTPClient interface {
	CheckHealth(ctx context.Context, req *CheckHealthRequest, opts ...http.CallOption) (rsp *CheckHealthReply, err error)
}

type MonitorHTTPClientImpl struct {
	cc *http.Client
}

func NewMonitorHTTPClient(client *http.Client) MonitorHTTPClient {
	return &MonitorHTTPClientImpl{client}
}

func (c *MonitorHTTPClientImpl) CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...http.CallOption) (*CheckHealthReply, error) {
	var out CheckHealthReply
	pattern := "/checkhealth"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.healthz.v1.Monitor/CheckHealth"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
